blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/databento/epoch/discussions
    about: Please ask questions like "How do I achieve x?" here.
  - name: DatabentoHQ
    url: https://x.com/DatabentoHQ
    about: Follow us on X for news and updates!
